[FEATURE] Profile module - Favorite recruit API
peer-42seoul/Peer-Backend pull request #125
Opened 2023-10-21 15:33 UTC by juhyeonlee134

## 변경 사항

- 관심 목록을 조회하는 API를 구현했습니다.
- 관심 목록을 전부 삭제하는 API를 구현했습니다.

<br><br><br>
## 테스트 결과

- 서비스는 단위 테스트 진행했고, 컨트롤러는 데이터 베이스에 직접 데이터를 넣어서 Postman으로 확인했습니다.

2023-10-21 15:33 UTC, sinryuji commented
🎉 @Paul2021-R 님 랜덤 리뷰어로 당첨되셨습니다! 리뷰를 부탁드립니다. 🙏
🎉 @perman0519 님 랜덤 리뷰어로 당첨되셨습니다! 리뷰를 부탁드립니다. 🙏

2023-10-22 02:50 UTC, Paul2021-R requested changes

2023-10-22 02:50 UTC, Paul2021-R commented on backend/src/main/java/peer/backend/dto/profile/response/FavoriteResponse.java
> +    boolean isFavorite;
확인 필요.Postman에서 정상적으로 isFavorite 로 나오는지 확인해주세요~

2023-10-24 03:22 UTC, perman0519 approved these changes

2023-10-24 03:22 UTC, perman0519 commented on backend/src/main/java/peer/backend/dto/profile/response/FavoriteResponse.java
> +    boolean isFavorite;
불리언값은 josn에서 멀로 나와요?

2023-10-24 04:05 UTC, juhyeonlee134 commented on backend/src/main/java/peer/backend/dto/profile/response/FavoriteResponse.java
> +    boolean isFavorite;
불리언 값은 true / false로 나옵니다

2023-10-24 04:46 UTC, juhyeonlee134 commented on backend/src/main/java/peer/backend/dto/profile/response/FavoriteResponse.java
> +    boolean isFavorite;
RecruitFavorite 엔티티에 있는 Boolean값인 likes가 의미가 없어서 저는 FavoriteResponse DTO에서만 수정했고, jwee님이 엔티티에서 수정하기로 했습니다.

2023-10-24 05:14 UTC, Paul2021-R approved these changes
![image](https://github.com/peer-42seoul/Peer-Backend/assets/80471693/df9a2904-1b35-4ac1-937f-322751c562ba)

2023-10-24 05:14 UTC, merged