[FEATURE] #158 taglist write form add
peer-42seoul/Peer-Backend pull request #160
Opened 2023-10-24 13:29 UTC by weejihye

## 변경 사항

모집글 작성시 태그리스트 반환,
모집글 수정시 기존 정보 로드 메소드 추가

<br><br><br>
## 테스트 결과

2023-10-24 13:30 UTC, sinryuji commented
🎉 @sinryuji 님 랜덤 리뷰어로 당첨되셨습니다! 리뷰를 부탁드립니다. 🙏
🎉 @perman0519 님 랜덤 리뷰어로 당첨되셨습니다! 리뷰를 부탁드립니다. 🙏

2023-10-25 04:46 UTC, perman0519 requested changes
댓글남겼습니다

2023-10-25 04:46 UTC, perman0519 commented on backend/src/main/java/peer/backend/controller/board/RecruitController.java
> +    public void applyRecruit(@PathVariable Long recruit_id, @RequestBody ApplyRecruitRequest request){
Authentication 객체를 왜 안받으셨나요??

2023-10-25 04:46 UTC, perman0519 commented on backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
> +                .nickname(userRepository.findById(request.getUser_id()).get().getNickname())
여기서 findby 안하고 바로 쓸 수 있을거같은데

2023-10-25 04:47 UTC, perman0519 approved these changes

2023-10-25 05:05 UTC, sinryuji commented on backend/src/main/java/peer/backend/controller/board/RecruitController.java
> +    public void applyRecruit(@PathVariable Long recruit_id, @RequestBody ApplyRecruitRequest request){
저도 user id를 바디로 받지 말고 Authentication의 유저에 아이디를 이용하시는게 더 좋을 것 같습니다

2023-10-25 05:05 UTC, sinryuji commented on backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
> +            throw new IllegalArgumentException("이미 지원한 팀입니다.");
IllegalArgumentException을 던지면 어느 HTTP 코드를 리턴하나요?

2023-10-25 05:24 UTC, weejihye commented on backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
> +            throw new IllegalArgumentException("이미 지원한 팀입니다.");
auth는 한꺼번에 수정하기 위해서 따로 pr을 올렸습니다.
illegalArgumentException은 400을 리턴합니다~

2023-10-25 05:25 UTC, weejihye commented on backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
> +            throw new IllegalArgumentException("이미 지원한 팀입니다.");
auth는 한꺼번에 수정하기 위해서 해당 작업분만 따로 Pr을 올렸습니다.

2023-10-25 05:42 UTC, sinryuji commented on backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
> +            throw new IllegalArgumentException("이미 지원한 팀입니다.");
기존의 데이터와 충돌되는 요청이라 400보다 409가 맞은거 같은데 어떻게 생각하시나요?

2023-10-25 06:25 UTC, sinryuji approved these changes
전부 확인하였습니다~

2023-10-25 07:48 UTC, weejihye commented on backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
> +            throw new IllegalArgumentException("이미 지원한 팀입니다.");
이미 존재하는 리소스에 대한 충돌이기 때문에 409가 더 적당할 것 같습니다. api문서와 코드 수정해서 commit 다시 올릴게요~

2023-10-25 08:02 UTC, merged