258 hotfix profile controller and dto
peer-42seoul/Peer-Backend pull request #272
Opened 2023-11-08 05:22 UTC by juhyeonlee134

## 변경 사항

- boolean 값을 Boolean으로 변경했으나, form-data로부터 boolean 값을 가져오기 위해 String으로 변경했습니다.
- 이미지 저장 위치는 아직 결정난 것이 없어 그대로 유지했습니다.

<br><br><br>
## 테스트 결과

2023-11-08 05:22 UTC, sinryuji commented
🎉 @Paul2021-R 님 랜덤 리뷰어로 당첨되셨습니다! 리뷰를 부탁드립니다. 🙏
🎉 @perman0519 님 랜덤 리뷰어로 당첨되셨습니다! 리뷰를 부탁드립니다. 🙏

2023-11-08 06:50 UTC, perman0519 commented
boolean을 Boolean으로 바꾼이유가 있나요??

2023-11-08 06:51 UTC, perman0519 approved these changes
대문자로 변경 확인 유효성체크 확인

2023-11-08 06:58 UTC, juhyeonlee134 commented
> boolean을 Boolean으로 바꾼이유가 있나요??
포스트맨으로 테스트 할 때, boolean값이 null로 들어오는 경우가 있어서 null도 받을 수 있도록 Boolean으로 변경했습니다

2023-11-08 08:18 UTC, Paul2021-R requested changes
개인적으로 DTO 값에서 String 을 그대로 Boolean 처럼 생각하고 쓰는거보단, 
커스텀 어노테이션으로 만들어서 썼으면 합니다..! 

----
chatGPT 조언 첨부

네, 스프링 부트에서 커스텀 어노테이션을 사용하여 request 값 중 스트링을 boolean으로 형변환할 수 있습니다. 이를 위해 다음의 단계를 따를 수 있습니다:

1. 커스텀 어노테이션을 생성하고, 어노테이션을 사용할 메소드나 클래스에 적용합니다.
2. 커스텀 어노테이션 내에서 스트링 값을 boolean으로 형변환하는 코드를 작성합니다. 이를 위해 Java의 `Boolean.parseBoolean()` 메소드를 사용할 수 있습니다.
3. 스프링 부트에서 제공하는 AOP (Aspect-Oriented Programming)를 활용하여 커스텀 어노테이션이 적용된 메소드의 파라미터를 변경합니다.

이렇게 하면 실제 컨트롤러에 들어오는 값이 boolean으로 변환될 것입니다. 단, 이 작업은 조심스럽게 처리해야하며, 형변환이 제대로 이루어지지 않을 경우 예외 처리를 고려해야 합니다.

2023-11-08 08:18 UTC, Paul2021-R commented on backend/src/main/java/peer/backend/controller/profile/ProfileController.java
Valid 넣어랏!

2023-11-08 11:38 UTC, juhyeonlee134 commented on backend/src/main/java/peer/backend/controller/profile/ProfileController.java
이거 어노테이션 하나 만들기에는 규모가 너무 커져버려서 그냥 Controller에서 Convert하는 preivate 메서드 하나 만들어서 Service에 전달하는 방식으로 했습니다.

2023-11-09 07:28 UTC, Paul2021-R approved these changes
거 맨날 일커진다고 안하면 언제 해본데....

2023-11-09 07:33 UTC, merged