[FEAT] : Add nhn Object storage
peer-42seoul/Peer-Backend pull request #391
Opened 2023-11-21 08:07 UTC by perman0519

## 변경 사항

File 업로드를 nhn Object storage에 업로드 합니다

<br><br><br>
## 테스트 결과

테스트 postMan으로 통과

2023-11-21 08:07 UTC, sinryuji commented
🎉 @weejihye 님 랜덤 리뷰어로 당첨되셨습니다! 리뷰를 부탁드립니다. 🙏

2023-11-21 09:09 UTC, weejihye approved these changes
- nhn 토큰 issue, refresh
- token 적용한 upload, delete 메소드
- upload에서 requestCallBack을 이용하여 file InputStream 을 복사하여 전송
상기 내용 확인했습니다.

의견
반복되는(그리고 앞으로 반복될 것 같은) 토큰 만료 확인 및 Refresh를 분리 혹은 issue코드에 포함하면 어떨까요?

2023-11-21 11:07 UTC, weejihye requested changes

2023-11-21 11:07 UTC, weejihye commented on backend/src/main/java/peer/backend/controller/team/TeamController.java
>      public static final String TEAM_URL = "/api/v1/team";
해당 내용 annotation으로 처리 하면 좋을 것 같아요. @RequestMapping을 사용하시면 됩니다.

2023-11-21 11:21 UTC, weejihye reviewed
implementation 'org.apache.httpcomponents:httpclient:4.5.13'
implementation 'org.apache.httpcomponents:httpcore:4.4.14'

해당 dependancy에서 기존 어플리케이션과 충돌을 일으켜 삭제합니다.
해당 dependanc가 없어도 기존 코드 제대로 동작합니다.

2023-11-22 05:32 UTC, weejihye approved these changes
restTemplate bean 등록하고 minor한 refactoring 진행했습니다. 고생하셨습니다~

2023-11-22 05:32 UTC, merged