[FEAT] 알림 모듈 02-04 부분 구현
peer-42seoul/Peer-Backend pull request #474
Opened 2023-12-05 09:47 UTC by wochae

## 구현 사항

알람 모듈에서 디비에 생성 및 삭제하는 기능을 구현했습니다.
소나한테 먼저 맞는 매.

<br><br><br>
## 테스트 결과

2023-12-05 09:47 UTC, sinryuji commented
🎉 @Paul2021-R 님 랜덤 리뷰어로 당첨되셨습니다! 리뷰를 부탁드립니다. 🙏

2023-12-06 08:57 UTC, Paul2021-R requested changes

2023-12-06 08:57 UTC, Paul2021-R commented on src/main/java/peer/backend/entity/alarm/Alarm.java
> +    private Long target;
OneToMany 타입으로 리스트 테이블을 Join하고
List <Long> User ID만을 기반으로한다. 

아이디어 )
타겟 테이블에 각 유저의 옵션 값을 넣어준다. 이로써 알람의 효율적인 전달, 검증을 돕는다.

2023-12-06 08:57 UTC, Paul2021-R commented on src/main/java/peer/backend/entity/alarm/Alarm.java
> +
알람 create : 
1. 알람생성, total count = 30, delete =  0
2. targetTable update 

알람 삭제 요청 
1. user 1명이 요청 
2. 자기 자신에 대한 targeTable delete 처리 -> alarmId + userId => 1개 
3. 전체 event에 대한 삭제 처리 여부 => delete ++ 
4. total = delete => 해당 이벤트를 받은 모든 사람이 삭제를 한것으로 판단 => 이벤트를 지우면, OneToMany, Cascade, targetTable 은 알아서 갱신이 되도록 한다.

2023-12-06 08:57 UTC, Paul2021-R commented on src/main/java/peer/backend/entity/alarm/Alarm.java
> +
total, delete counter가 없을시 로직 
1. user 1명이 요청 
2. event를 요청, List<target> 
3. user에 대해 처리를 완료(delete) 
4. List<target> .size = total counter 
5. target.delete 여부는 for문을 돌든가 해야함 -> delete++

2023-12-06 08:57 UTC, Paul2021-R commented on src/main/java/peer/backend/entity/alarm/Subscription.java
> +    private String key;
firebaseToken

2023-12-06 08:57 UTC, Paul2021-R commented on src/main/java/peer/backend/controller/NotiController.java
> +}
subscriptionPWA(subscritpion dto ) API 하나 있어야함

2023-12-06 08:57 UTC, Paul2021-R commented on src/main/java/peer/backend/service/alarm/AlarmServiceImpl.java
> +        alarmRepository.save(data);
public injectAlarm(type, priority, title, message, List<User>, URL)

2023-12-22 09:50 UTC, closed without merging