56 feat profile module personal information api
peer-42seoul/Peer-Backend pull request #80
Opened 2023-10-10 12:35 UTC by juhyeonlee134

## 변경 사항

C-MYPAGE-09에 해당하는, 사용자 개인정보 조회 API를 구현했습니다.

<br><br><br>
## 테스트 결과

단위 테스트를 진행했고, Postman으로 확인했습니다.

2023-10-11 11:40 UTC, weejihye requested changes
"존재하지 않는 비밀번호입니다."라는 문구가 어색해요~ 수정이 필요하지 않을까?

2023-10-11 14:07 UTC, weejihye approved these changes
확인 했습니다

2023-10-12 08:35 UTC, perman0519 commented
확인했습니다 Responce 생성자대신 Builder쓰신 이유가 있으신가요??

2023-10-12 08:35 UTC, perman0519 approved these changes
비밀번호 정책은 나중에 더 정해지겠죠??

2023-10-12 08:43 UTC, juhyeonlee134 commented
> 확인했습니다 Responce 생성자대신 Builder쓰신 이유가 있으신가요??
생성자를 사용할 때보다 가독성이 좋고, 데이터 순서 상관없이 사용할 수 있어서 Builder를 사용했습니다

2023-10-12 08:54 UTC, juhyeonlee134 commented
> 비밀번호 정책은 나중에 더 정해지겠죠??

우선 이전에 정했던 비밀번호 정책을 기반으로 구현하긴 했습니다. 이후에 정책이 확정되는데로 추가할 예정입니다

2023-10-12 08:54 UTC, merged